name: Go

on:
  push:
    branches: [ main, develop, project/*, feat/*, fix/*, ci/* ]
  pull_request:
    branches: [ main, develop, project/* ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Test
      run: go test -v ./...
      env:
        FUGLE_API_TOKEN: ${{ secrets.FUGLE_API_TOKEN }}

    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        golint ./...
